services:
  
  postgres:
    image: postgres:16-alpine
    container_name: skllr_reward_postgres
    env_file:
      - .env.docker
    ports:
      - "5445:5432"
    volumes:
      - reward_pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
      

  reward:
    container_name: skllr_reward_api
    build:
      context: ../..
      dockerfile: apps/reward/dockerfile.reward
    env_file:
      - .env.docker
    ports:
      - "3003:3003"
    depends_on:
      postgres: 
        condition: service_healthy
      minio:
        condition: service_started
    restart: unless-stopped
    mem_limit: 2g
    cpus: 1.0

volumes:
  reward_pg_data:
  minio_data:
