services:
  postgres:
    image: postgres:16-alpine
    container_name: skillr_quizs_postgres
    env_file:
      - .env.docker
    ports:
      - "5440:5432"
    volumes:
      - quizs_pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quizs_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  quizs:
    container_name: skillr_quizs_api
    build:
      context: ../..
      dockerfile: apps/quizs/dockerfile.quizs
    env_file:
      - .env.docker
    ports:
      - "3003:3003"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  quizs_pg_data:
