services:
  postgres:
    image: postgres:16-alpine
    container_name: skillr_course_postgres
    env_file:
      - .env.docker
    ports:
      - "5435:5432"
    volumes:
      - course_pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: skillr_course_redis
    command: redis-server --appendonly yes
    environment:
      TZ: Asia/Bangkok
    ports:
      - "6379:6379"
    volumes:
      - course_redis_data:/data
    restart: unless-stopped

  course:
    container_name: skillr_course_api
    build:
      context: ../..
      dockerfile: apps/course-service/dockerfile.course
    env_file:
      - .env
    environment:
      TZ: Asia/Bangkok
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

volumes:
  course_pg_data:
  course_redis_data:
  course_minio_data: