export const THAI_STOCKS = [
  "ADVANC","AOT","AWC","BANPU","BBL","BDMS","BEM","BGRIM","BH","BJC",
  "CBG","CENTEL","COM7","CPALL","CPF","CPN","CRC","DELTA","EA","EGCO",
  "GLOBAL","GPSC","GULF","HMPRO","INTUCH","IRPC","IVL","KBANK","KCE","KTB",
  "KTC","LH","MINT","MTC","OR","OSP","PTT","PTTEP","PTTGC","RATCH","SAWAD",
  "SCB","SCC","SCGP","TIDLOR","TISCO","TLI","TOP","TRUE","TU","WHA",
  "AMATA","AP","BCP","BLA","BTG","CK","CKP","DOHOME","ERW","GFPT","JMT",
  "JMART","KKP","MEGA","ORI","PRM","PSL","RBF","SINGER","SPALI","STA",
  "STGT","TASCO","TCAP","THANI","TKN","TTB","VGI","WICE","XO",
];