import { MigrationInterface, QueryRunner } from "typeorm";

export class ArticleCardsUpdate1769496223892 implements MigrationInterface {
    name = 'ArticleCardsUpdate1769496223892'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Drop FKs that depend on the PKs we want to change
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT IF EXISTS "FK_b29e83fed739900987f874ca6b8"`);
        
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT IF EXISTS "FK_f31484333cb2c0f6c83272d26e3"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP CONSTRAINT IF EXISTS "FK_6ad0e14c0f76dc58f3180a35820"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP CONSTRAINT IF EXISTS "FK_05595d7c0de76a1f3547fac568a"`);
        await queryRunner.query(`DROP INDEX "public"."idx_courses_course_owner_id"`);
        await queryRunner.query(`CREATE TABLE "article_cards" ("id" SERIAL NOT NULL, "article_id" integer NOT NULL, "content" text NOT NULL, "media_url" character varying(255), "sequence_order" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8e601fee9eab7bd99963305eabf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "PK_b9a16e8d0dc20426e1611e560bc"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "article_id"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "article_content"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "article_image_id"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "PK_738fd696873afdde0c2ee567a01"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP COLUMN "lesson_id"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP COLUMN "lesson_title"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP COLUMN "lesson_description"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP COLUMN "chapterChapterId"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP CONSTRAINT "PK_e4b8449ce68d3f471e71036eb8b"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP COLUMN "chapter_id"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP COLUMN "chapter_title"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP COLUMN "chapter_name"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP COLUMN "chapter_type"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP COLUMN "chapter_description"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP COLUMN "levelLevelId"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP CONSTRAINT "PK_5f4d4290a9bd9530919c2fd6e2e"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP COLUMN "level_id"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP COLUMN "level_title"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP COLUMN "courseCourseId"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "PK_42dc69837b2e7bc603686ddaf53"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "course_id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "course_owner_id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "course_title"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "course_description"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "course_image_id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "course_tags"`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "PK_0a6e2c450d83e0b6052c2793334" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "content" jsonb`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "PK_9b9a8d455cac672d262d7275730" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD "title" character varying NOT NULL DEFAULT 'Untitled Lesson'`);
        await queryRunner.query(`ALTER TABLE "lessons" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD "description" text`);
        await queryRunner.query(`CREATE TYPE "public"."lessons_ref_source_enum" AS ENUM('course', 'media', 'quiz')`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD "ref_source" "public"."lessons_ref_source_enum" NOT NULL DEFAULT 'course'`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD "chapterId" integer`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD CONSTRAINT "PK_a2bbdbb4bdc786fe0cb0fcfc4a0" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD "title" character varying NOT NULL DEFAULT 'Untitled Chapter'`);
        await queryRunner.query(`ALTER TABLE "chapters" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD "levelId" integer`);
        await queryRunner.query(`ALTER TABLE "levels" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "levels" ADD CONSTRAINT "PK_05f8dd8f715793c64d49e3f1901" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "levels" ADD "title" character varying NOT NULL DEFAULT 'Untitled Level'`);
        await queryRunner.query(`ALTER TABLE "levels" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "levels" ADD "courseId" integer`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "owner_user_id" integer NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "owner_user_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "title" character varying NOT NULL DEFAULT 'Untitled Course'`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "cover_media_asset_id" integer`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "intro_media_asset_id" integer`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "estimate_time_seconds" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "category_id" integer`);
        await queryRunner.query(`ALTER TYPE "public"."lessons_type_enum" RENAME TO "lessons_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."lessons_type_enum" AS ENUM('article', 'video', 'quiz', 'assignment')`);
        await queryRunner.query(`ALTER TABLE "lessons" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "lessons" ALTER COLUMN "type" TYPE "public"."lessons_type_enum" USING "type"::"text"::"public"."lessons_type_enum"`);
        await queryRunner.query(`ALTER TABLE "lessons" ALTER COLUMN "type" SET DEFAULT 'article'`);
        await queryRunner.query(`DROP TYPE "public"."lessons_type_enum_old"`);
        await queryRunner.query(`CREATE INDEX "idx_courses_owner_user_id" ON "courses" ("owner_user_id") `);
        await queryRunner.query(`ALTER TABLE "article_cards" ADD CONSTRAINT "FK_60d53fc355ae423bc7a954371c4" FOREIGN KEY ("article_id") REFERENCES "articles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_1067c75d93c6ce6408cd1ad156a" FOREIGN KEY ("chapterId") REFERENCES "chapters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD CONSTRAINT "FK_f1a610efcad0b35eda552d40e03" FOREIGN KEY ("levelId") REFERENCES "levels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "levels" ADD CONSTRAINT "FK_22f6d6693a6c24ff83076e60837" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "levels" DROP CONSTRAINT "FK_22f6d6693a6c24ff83076e60837"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP CONSTRAINT "FK_f1a610efcad0b35eda552d40e03"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_1067c75d93c6ce6408cd1ad156a"`);
        await queryRunner.query(`ALTER TABLE "article_cards" DROP CONSTRAINT "FK_60d53fc355ae423bc7a954371c4"`);
        await queryRunner.query(`DROP INDEX "public"."idx_courses_owner_user_id"`);
        await queryRunner.query(`CREATE TYPE "public"."lessons_type_enum_old" AS ENUM('article', 'video', 'quiz')`);
        await queryRunner.query(`ALTER TABLE "lessons" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "lessons" ALTER COLUMN "type" TYPE "public"."lessons_type_enum_old" USING "type"::"text"::"public"."lessons_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "lessons" ALTER COLUMN "type" SET DEFAULT 'article'`);
        await queryRunner.query(`DROP TYPE "public"."lessons_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."lessons_type_enum_old" RENAME TO "lessons_type_enum"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "estimate_time_seconds"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "intro_media_asset_id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "cover_media_asset_id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "owner_user_id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP COLUMN "courseId"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP CONSTRAINT "PK_05f8dd8f715793c64d49e3f1901"`);
        await queryRunner.query(`ALTER TABLE "levels" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP COLUMN "levelId"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP CONSTRAINT "PK_a2bbdbb4bdc786fe0cb0fcfc4a0"`);
        await queryRunner.query(`ALTER TABLE "chapters" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP COLUMN "chapterId"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP COLUMN "ref_source"`);
        await queryRunner.query(`DROP TYPE "public"."lessons_ref_source_enum"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "PK_9b9a8d455cac672d262d7275730"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "content"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "PK_0a6e2c450d83e0b6052c2793334"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "course_tags" text array`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "course_image_id" integer`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "course_description" text`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "course_title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "course_owner_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "course_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "PK_42dc69837b2e7bc603686ddaf53" PRIMARY KEY ("course_id")`);
        await queryRunner.query(`ALTER TABLE "levels" ADD "courseCourseId" integer`);
        await queryRunner.query(`ALTER TABLE "levels" ADD "level_title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "levels" ADD "level_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "levels" ADD CONSTRAINT "PK_5f4d4290a9bd9530919c2fd6e2e" PRIMARY KEY ("level_id")`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD "levelLevelId" integer`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD "chapter_description" text`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD "chapter_type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD "chapter_name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD "chapter_title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD "chapter_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD CONSTRAINT "PK_e4b8449ce68d3f471e71036eb8b" PRIMARY KEY ("chapter_id")`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD "chapterChapterId" integer`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD "lesson_description" text`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD "lesson_title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD "lesson_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "PK_738fd696873afdde0c2ee567a01" PRIMARY KEY ("lesson_id")`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "article_image_id" integer`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "article_content" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "article_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "PK_b9a16e8d0dc20426e1611e560bc" PRIMARY KEY ("article_id")`);
        await queryRunner.query(`DROP TABLE "article_cards"`);
        await queryRunner.query(`CREATE INDEX "idx_courses_course_owner_id" ON "courses" ("course_owner_id") `);
        await queryRunner.query(`ALTER TABLE "levels" ADD CONSTRAINT "FK_05595d7c0de76a1f3547fac568a" FOREIGN KEY ("courseCourseId") REFERENCES "courses"("course_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapters" ADD CONSTRAINT "FK_6ad0e14c0f76dc58f3180a35820" FOREIGN KEY ("levelLevelId") REFERENCES "levels"("level_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_f31484333cb2c0f6c83272d26e3" FOREIGN KEY ("chapterChapterId") REFERENCES "chapters"("chapter_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
